steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ml-deploy-artifact/model-image-last"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ml-deploy-artifact/model-image-last"
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "api-service-backend"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/ml-deploy-artifact/model-image-last"
      - "--region=us-central1"
      - "--cpu=1"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=BUCKET_NAME=bucket_name:latest"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/ml-deploy-artifact/model-image-last"
logsBucket: "gs://ml-deploy-110803/logs"
